StudioBonito\SilverStripe\Queue\QueueManager:
  default: 'sync'
  sync:
    driver: 'sync'
  db:
    driver: 'db'
    queue: 'default'
  beanstalkd:
    driver: 'beanstalkd'
    host: 'localhost'
    queue: 'default'
    ttr: 60